Controversy and Uncertainty
24-S1-2-C-Moral-Decisions/moral-survey pull request #24
Opened 2024-08-07 05:15 UTC by Universe-E

1. Add: moral-survey-3
2. Refactor: understandTopic.html, twoStageSurvey.html, study-model.js

2024-08-07 07:11 UTC, Valencia-Choi approved these changes
Great

2024-08-11 03:18 UTC, Xinlong-Wu requested changes
main branch has changes, please update and solve the conflicts

2024-08-11 08:56 UTC, Xinlong-Wu requested changes
please address comments

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/img/controversy&uncertainty/2-YA-98-NA.png
don't put them into `img/controversy&uncontroversy`, cuz it might be update in the feature.

please put example picture at folder `img/`

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/img/controversy&uncertainty/51-YA-49-NA.png
same

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/twoStageSurvey.html
> -
that should be the content of Survey 1.

Did you make sure there is nothing changed to it?

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/twoStageSurvey.html
> +                <p id="training-end" class="fs-5 pt-4 bolded-blue" data-i18n="moral-training-end"></p>
why change font size here?

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/twoStageSurvey.html
> -            <div class="fs-6 p-4">
why change font size and style here?

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/twoStageSurvey.html
> +            <h4 class="bolded-blue" data-i18n="moral-training-note-desc">###</h4>
there may not all survey has a description.

please refer to https://github.com/24-S1-2-C-Moral-Decisions/moral-survey/blob/f282006dc1da02ec12506d715fa978439510dc71/src/templates/twoStageSurvey.html#L7-L20

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/twoStageSurvey.html
> -            <h4 class="bolded-blue" data-i18n="moral-training-task2-{{topic}}"></h4>
please make sure this change will not influence other survey and future survey

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> -    <h2 class="bolded-blue" data-i18n="moral-topic-understand-{{topic}}">###</h1>
why change font size here?
please make sure this change will not influence other survey and future survey

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> +                <span data-i18n="moral-topic-reddit-controversy-uncertainty-summary">###</span>
please make sure this change will not influence other survey and future survey

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> -            <div class="p-3">
why change font size here?

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> -            <div class="p-3">
why change font size here?

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> -            <div class="p-3">
why change font size here?

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> +                <h3 class="bolded-blue" data-i18n="moral-topic-what-is-controversy">###</h3>
please make sure this change will not influence other survey and future survey

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> +                        <u data-i18n="moral-topic-high-controversy">###</u>
please make sure this change will not influence other survey and future survey

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> +                        <u data-i18n="moral-topic-low-controversy">###</u>
please make sure this change will not influence other survey and future survey

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> +                    <span data-i18n="moral-topic-practice-question">###</span>
please make sure this change will not influence other survey and future survey

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> -                <img class="img-fluid" src="../img/{{topic}}_example.png" alt="{{topic}}_example">
please make sure this change will not influence other survey and future survey

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> -                        {{#if isCon}}
please make sure this change will not influence other survey and future survey

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> -                        {{/if}}
please make sure this change will not influence other survey and future survey

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> -                            <p class="survey1-paragraph-body mid-font bolded-blueer" data-i18n='moral-topic-practice-question-{{topic}}-ans-p1' ></p>
please make sure this change will not influence other survey and future survey

2024-08-11 08:56 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> -                            <span class="survey1-paragraph-body mid-font bolded-blueer" data-i18n='moral-topic-practice-question-{{topic}}-ans2-s1'></span>
please make sure this change will not influence other survey and future survey

2024-08-21 07:04 UTC, Xinlong-Wu commented on src/moral-survey-3/study-model.js
> +			topic: "controversy",
why not change function `LITW.data.getTopic()`

2024-08-21 07:04 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> +    <h2 class="bolded-blue" data-i18n="moral-topic-understand-controversy-uncertainty">###</h2>
will it influence other survey?

2024-08-21 07:04 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> +            <div>
why change font size here?

2024-08-21 07:04 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> +                    <img class="img-fluid" src="../img/2-YA-98-NA.png" alt="controversy&uncertainty">
do not name image by an unspecific name.
eg. please declare  it is a example of certainty&uncertainty

2024-08-21 07:04 UTC, Xinlong-Wu commented on src/templates/understandTopic.html
> +                            </div>
why add it? what is these line for? is it related to your survey?

2024-08-24 12:25 UTC, merged